import { SiteContent } from './types';

export const initialSiteContent: SiteContent = {
  business: {
    brandName: 'Satria Musik & Box Speaker',
    tagline: 'Studio Latihan Musik & Pembuatan Box Speaker',
    ownerName: 'Pak Aris Satria',
    whatsappNumber: '0812-9877-2232',
    whatsappRaw: '6281298772232',
    studioAddress: 'Jl. Kw. Industri Tristate, Sukadamai, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    workshopAddress: 'Satria Musik Studio, RT002 RW001, Jl. Kw. Industri Tristate, Sukadamai, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    studioMapsUrl: 'https://maps.app.goo.gl/PY5R6Sj5UQPyQnnM8?g_st=ic',
    workshopMapsUrl: 'https://maps.app.goo.gl/rENBaAuSVQy5r3n38?g_st=ic',

    openHoursStudio: 'Setiap Hari • 09.00 - 24.00 WIB',
    openHoursWorkshop: 'Senin - Sabtu • 08.30 - 17.30 WIB',
  },
  hero: {
    badgeText: 'Usaha Studio Musik & Pembuatan Box Speaker — Pak Aris Satria',
    title: 'Studio Musik & Pembuatan Custom Box Speaker',
    description: 'Penyewaan studio latihan band ber-AC dengan alat lengkap, serta melayani pesanan pembuatan box speaker dari bahan kayu multiplek berkualitas untuk sound system dan rumahan.',
  },
  studio: {
    title: 'Studio Latihan Musik',
    description: 'Ruang latihan nyaman dengan pendingin ruangan (AC), peredam suara yang baik, dan alat musik lengkap yang selalu dirawat.',
    facilities: [
      {
        id: 'fac-1',
        title: 'Ruangan Ber-AC & Peredam',
        desc: 'Ruang latihan sejuk dan nyaman untuk latihan berjam-jam bersama teman band.',
      },
      {
        id: 'fac-2',
        title: 'Drum Set Terawat',
        desc: 'Set drum lengkap dengan pedal dan simbal siap pakai dengan suara yang mantap.',
      },
      {
        id: 'fac-3',
        title: 'Ampli Gitar & Bass',
        desc: 'Tersedia amplifier gitar dan bass dengan karakter suara yang jelas.',
      },
      {
        id: 'fac-4',
        title: 'Sound & Mic Vokal',
        desc: 'Mikrofon dan speaker monitor vokal yang jernih agar artikulasi vokal jelas terdengar.',
      },
    ],
  },
  boxSpeaker: {
    title: 'Pembuatan Box Speaker',
    description: 'Menerima pesanan pembuatan berbagai jenis box speaker yang dibuat langsung oleh Pak Aris Satria dengan bahan kayu multiplek pilihan dan pengerjaan yang rapi serta kokoh.',
    features: [
      {
        title: 'Bahan Multiplek Berkualitas',
        desc: 'Menggunakan bahan kayu multiplek / triplek yang tebal dan padat sehingga box kuat dan tidak mudah rusak.',
      },
      {
        title: 'Finishing Rapi & Tahan Cuaca',
        desc: 'Dilapisi cat tekstur pelindung yang tahan air dan tidak mudah lecet saat dibawa manggung.',
      },
      {
        title: 'Bisa Custom Model & Ukuran',
        desc: 'Bisa disesuaikan dengan ukuran driver speaker yang Anda miliki atau skema box favorit Anda.',
      },
    ],
    models: [
      {
        id: 'mod-1',
        name: 'Box Subwoofer (Planar / CLA / Miniscoop)',
        desc: 'Cocok untuk nada rendah (bass) yang padat dan bertenaga untuk sound lapangan maupun acara.',
      },
      {
        id: 'mod-2',
        name: 'Box Line Array & Middle',
        desc: 'Untuk karakter vokal dan nada menengah agar suara lontaran tembak jauh dan terdengar jelas.',
      },
      {
        id: 'mod-3',
        name: 'Box Monitor Panggung',
        desc: 'Model miring untuk monitor pemain di atas panggung agar musik terdengar nyaman saat tampil.',
      },
      {
        id: 'mod-4',
        name: 'Box Speaker Custom Lainnya',
        desc: 'Bisa membawa ukuran atau gambar skema sendiri sesuai kebutuhan dan kapasitas ruangan.',
      },
    ],
  },
  about: {
    title: 'Tentang Usaha Kami',
    ownerImageUrl: '/images/box-custom-3.jpg',
    p1: 'Usaha ini dirintis dan dikelola langsung oleh Pak Aris Satria. Berawal dari hobi bermusik dan pengalaman di bidang perkayuan serta sound system, kami ingin menghadirkan tempat latihan musik yang nyaman sekaligus bengkel pembuatan box speaker dengan pengerjaan yang jujur dan rapi.',
    p2: 'Bahan kayu yang digunakan dipilih dengan baik tanpa campuran serbuk kayu murahan. Pengerjaan lem dan sekrup dipastikan rapat agar tidak bocor suara dan tahan lama untuk pemakaian jangka panjang.',
  },
  gallery: [
    {
      id: 'box-real-1',
      title: 'Custom Box Monitor Slope Black',
      category: 'box_speaker',
      imageUrl: '/images/box-custom-1.jpg',
      caption: 'Box speaker monitor panggung dengan finishing cat tekstur hitam rapi & presisi.',
    },
    {
      id: 'box-real-2',
      title: 'Proses Rakit Box Multiplek',
      category: 'box_speaker',
      imageUrl: '/images/box-custom-2.jpg',
      caption: 'Bahan kayu multiplek berkualitas tebal dengan pengerjaan sekrup & lem rapat.',
    },
    {
      id: 'box-real-3',
      title: 'Flight Case / Hardcase Satria',
      category: 'box_speaker',
      imageUrl: '/images/box-custom-3.jpg',
      caption: 'Hardcase tempat penyimpanan sound & aksesoris Satria Entertainment.',
    },
    {
      id: 'box-real-4',
      title: 'Box Subwoofer Custom Dual Port',
      category: 'box_speaker',
      imageUrl: '/images/box-custom-4.jpg',
      caption: 'Box subwoofer lapangan / hajatan dengan karakter bass padat bertenaga.',
    },
    {
      id: 'box-real-5',
      title: 'Pair Box Monitor Middle Grid',
      category: 'box_speaker',
      imageUrl: '/images/box-custom-5.jpg',
      caption: 'Pasangan box speaker monitor lengkap dengan ram grill pelindung depan.',
    },
    {
      id: 'studio-real-1',
      title: 'Tampilan Lengkap Studio Musik',
      category: 'studio',
      imageUrl: '/images/studio-hero.jpg',
      caption: 'Ruang latihan ber-AC sejuk dengan set drum lengkap, ampli Marshall, dan gitar.',
    },
    {
      id: 'studio-real-2',
      title: 'Ampli Marshall & Sudut Gitar',
      category: 'studio',
      imageUrl: '/images/studio-real-1.jpg',
      caption: 'Amplifier Marshall bertenaga, mik vokal, dan gitar di dinding peredam kayu.',
    },
    {
      id: 'studio-real-3',
      title: 'Set Drum & Simbal Meinl HCS',
      category: 'studio',
      imageUrl: '/images/studio-real-2.jpg',
      caption: 'Simbal drum berkualitas Meinl HCS untuk latihan band mantap.',
    },
  ],
  reviews: [
    {
      id: 'rev-1',
      customerName: 'Rian Pratama',
      roleOrBand: 'Gitaris — Band The Velvet',
      category: 'studio',
      rating: 5,
      date: 'Agustus 2024',
      comment: 'Studio musik paling recommended di Cikupa! AC-nya sejuk, drum Meinl HCS mantap, ampli Marshall gahar banget. Suasana akustik ruangannya enak gak bikin budek di telinga. Pak Aris juga ramah banget melayani kami latihan.',
      isVerified: true,
    },
    {
      id: 'rev-2',
      customerName: 'Hendra Kusuma',
      roleOrBand: 'Owner HK Sound System Rental',
      category: 'box_speaker',
      rating: 5,
      date: 'Agustus 2024',
      comment: 'Pesan 4 unit box subwoofer planar 18 inch bahan multiplek padat ke Pak Aris. Hasil pengerjaannya sangat presisi, lem rapat, cat tekstur tebal anti gores. Bass-nya bulet dan nendang jauh di lapangan. Mantap jiwa!',
      isVerified: true,
    },
    {
      id: 'rev-3',
      customerName: 'Bagus Aditya',
      roleOrBand: 'Bassist — Eclipse Rock Band',
      category: 'studio',
      rating: 5,
      date: 'Juli 2024',
      comment: 'Langganan latihan di sini tiap akhir pekan buat persiapan event manggung. Alat musiknya selalu terawat, kabel-kabel gak ada yang kresek-kresek, mic vokal jernih. Tarif sewanya juga sangat bersahabat!',
      isVerified: true,
    },
    {
      id: 'rev-4',
      customerName: 'Dedi Supriadi',
      roleOrBand: 'Event Organizer Tangerang',
      category: 'box_speaker',
      rating: 5,
      date: 'Juli 2024',
      comment: 'Beli box monitor panggung miring dan flight case custom di Satria Musik. Pengerjaan rapi, finishing rapi, tahan banting pas dibawa keliling event hajatan dan panggung outdoor. Recommended pol!',
      isVerified: true,
    },
    {
      id: 'rev-5',
      customerName: 'Fikri Alamsyah',
      roleOrBand: 'Drummer — Komunitas Musik Tangerang',
      category: 'studio',
      rating: 5,
      date: 'Juni 2024',
      comment: 'Jarang nemu studio yang rawat snare drum dan simbal sebaik Satria Musik. Pedal drum responsif, AC sejuk bener bikin betah jamming 3 jam nonstop tanpa gerah. Sukses terus buat Pak Aris!',
      isVerified: true,
    },
    {
      id: 'rev-6',
      customerName: 'Wahyu Setiawan',
      roleOrBand: 'Pecinta Audio Rumahan & Mini Cafe',
      category: 'box_speaker',
      rating: 5,
      date: 'Mei 2024',
      comment: 'Bikin custom box subwoofer 12 inch buat audio cafe dan kamar. Skema sesuai request, kayu multiplek tebal no abal-abal. Suara bass empuk gak dengung. Pelayanan Pak Aris sangat komunikatif!',
      isVerified: true,
    },
  ],
};

